In [4]:
import numpy as np 
X1 = np.array([[1, -1, 1, -1]])
X2 = np.array([[-1, -1, 1, 1]])
X3 = np.array([[1, 1, -1, -1]])
X4 = np.array([[1, 1, 1, 1]])
X = [X1, X2, X3, X4]

In [5]:
Y1 = np.array([[1, 0, 1]])
Y2 = np.array([[1, 1, 1]])
Y3 = np.array([[0, 1, 1]])
Y4 = np.array([[1, 1, 0]])

Y = [Y1, Y2, Y3, Y4]


In [6]:
def calc_weight(X, Y):
    return np.dot(X.T, Y)

In [7]:
def calculate_weights(X, Y):
    weights = []
    for i in range(len(X)):
        weights.append(calc_weight(X[i], Y[i]))
    return weights

weights = calculate_weights(X, Y)

In [9]:
def forward_propagation(X, W):
    result = []
    for i in range(len(X)):
        result.append(X[i] @ W[i])
    return np.squeeze(result)

def Activation(X):
    X = np.array(X)
    X[ X > 0] = 1
    X[ X == 0] = 0
    X[ X < 0] = -1
    return X

In [11]:
forward_result = forward_propagation(X, weights)
print("Forward Propagation Output:", Activation(forward_result))

Forward Propagation Output: [[1 0 1]
 [1 1 1]
 [0 1 1]
 [1 1 0]]


In [13]:
def backward_propagation(X, W):
    result=[]
    
    for i in range(len(X)):
        result.append(W[i] @ X[i].T)
    return np.squeeze(result)
    

In [14]:
backward_result = backward_propagation(Y,weights)
print("Backward Propagation Output:",Activation(backward_result))

Backward Propagation Output: [[ 1 -1  1 -1]
 [-1 -1  1  1]
 [ 1  1 -1 -1]
 [ 1  1  1  1]]
